### GET USER
GET http://localhost:3000/auth/a41870bd-2b30-4e23-8805-37b48908f98a

### GET USERS
GET http://localhost:3000/auth?email=josh@ritter.com

### CREATE USER / SIGNUP
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test6@test.com",
  "password": "test3"
}

### SIGNIN
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "test1"
}

### GET PROFILE
GET http://localhost:3000/auth/profile


### SIGNOUT
POST http://localhost:3000/auth/signout

### Update user
PATCH  http://localhost:3000/auth/20ce0c62-adc6-4404-b8d1-23133e708a8f
Content-Type: application/json

{
  "email": "admin2@test.com",
  "test": "admin123"
}

### Delete user
DELETE http://localhost:3000/auth/8f83769c-3b51-4333-9ac4-a31ad15b2847
