### GET USER
GET http://localhost:3000/auth/20ce0c62-adc6-4404-b8d1-23133e708a8f

### GET USERS
GET http://localhost:3000/auth?email=admin2@test.com

### CREATE USER
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "stanley@kubrick.com",
  "password": "stanley"
}

### Update user
PATCH  http://localhost:3000/auth/20ce0c62-adc6-4404-b8d1-23133e708a8f
Content-Type: application/json

{
  "email": "admin2@test.com",
  "test": "admin123"
}

### Delete user
DELETE http://localhost:3000/auth/8f83769c-3b51-4333-9ac4-a31ad15b2847


